services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=920309
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_nextauth_project:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
  
  api:
    image: yjz039/api:latest
    container_name: api
    # network_mode: "host"
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - postgres
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
    # platform: "linux/amd64"   # 指定平台為 x86_64

  chatbot:
    image: yjz039/clone-gemini-chatbot:latest
    container_name: chatbot
    # build:
    #   context: ../clone-gemini-chatbot
    #   dockerfile: ./Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=postgres
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_DOMAIN=${NEXT_PUBLIC_API_DOMAIN}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - POSTGRES_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
volumes:
  postgres_data_nextauth_project: