services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=920309
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_nextauth_project:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
  
  # api:
  #   # image: yjz039/chatbotapi:v1
  #   container_name: api4
  #   # network_mode: "host"
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - postgres
  #   environment:
  #     - DB_USER=${DB_USER}
  #     - DB_HOST=postgres
  #     - DB_NAME=${DB_NAME}
  #     - DB_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data_nextauth_project: